add hr_employee_type (TA#15755)
Numigi/odoo-hr-addons pull request #15
Opened 2020-04-07 22:16 UTC by foutoucour

2020-04-07 22:18 UTC, foutoucour commented on hr_employee_type/__manifest__.py
> +{
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Statement seems to have no effect](https://app.codacy.com/manual/numigi/odoo-hr-addons/pullRequest?prid=5323856)

2020-04-07 22:18 UTC, foutoucour commented on hr_employee_type/models/hr_employee.py
> +from odoo import models, fields, api
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused api imported from odoo](https://app.codacy.com/manual/numigi/odoo-hr-addons/pullRequest?prid=5323856)

2020-04-07 22:19 UTC, foutoucour commented on hr_employee_type/models/hr_employee.py
> +from odoo import models, fields, api
```suggestion
from odoo import models, fields
```

2020-04-07 22:31 UTC, foutoucour commented on hr_employee_type/__manifest__.py
> +{
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Statement seems to have no effect](https://app.codacy.com/manual/numigi/odoo-hr-addons/pullRequest?prid=5323856)

2020-04-08 12:53 UTC, ddufresne requested changes
Commentaires mineurs seulement. Bon travail.

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/README.rst
> +This module adds the distinction between internal employee and external employee
Ça serait bien d'avoir des points à la fin des phrases. Il ne s'agit pas d'un titre/libellé ici.

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/models/hr_employee.py
> +        default=lambda record: record._context.get("search_default_ttype", "internal")
C'est un peu inhabituel ici. C'est mieux de juste avoir "default_ttype" dans ton contexte. Comme ça, pas besoin de la fonction lambda.

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/views/hr_employee.xml
> +        <field name="context">{ "search_default_ttype": "internal"}</field>
ajouter "default_ttype": "internal"

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/views/hr_employee.xml
> +        <field name="context">{ "search_default_ttype": "external"}</field>
same

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/views/hr_employee.xml
> +                <filter string="External" name="external" domain="[('ttype', '=', 'external')]"/>
:+1:

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/i18n/fr.po
> +msgstr "Employés Externes"
Employés Externes -> Employés externes

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/i18n/fr.po
> +msgstr "Employé Interne"
Employé Interne -> Employé interne

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/i18n/fr.po
> +msgstr "Employés Internes"
Employés Internes -> Employés internes

2020-04-08 12:53 UTC, ddufresne commented on hr_employee_type/i18n/fr.po
> +msgstr "Employé Externe"
Employé Externe -> Employé externe

2020-04-08 15:05 UTC, ddufresne approved these changes

2020-04-08 15:05 UTC, merged