TA#24250 Add chatter in payslip form view
Numigi/odoo-hr-addons pull request #19
Opened 2020-08-26 18:04 UTC by AmeGev

2020-09-21 22:00 UTC, qtiplb commented
@AmeGev c'est bien prêt pour révision ? J'ai ajouté @ddufresne pour la review.

2020-09-22 11:49 UTC, ddufresne requested changes
@AmeGev j'ai fait quelques simplifications.

- Le xpath est utilisé dans les cas plus complexes.
- Le groupe base correspond à tous les utilisateurs. Pas besoin de le mentionner.
- 'display_log_button': True est la valeur par défaut (par défaut, il est possible d'inscrire une note interne)

2020-09-22 11:49 UTC, ddufresne commented on hr_payslip_chatter/views/hr_payslip.xml
> +            </xpath>
```suggestion
            <sheet position="after">
                <div class="oe_chatter">
                    <field name="message_follower_ids" widget="mail_followers"/>
                    <field name="activity_ids" widget="mail_activity"/>
                    <field name="message_ids" widget="mail_thread"/>
                </div>
            </sheet>
```

2020-10-05 12:18 UTC, ddufresne approved these changes

2020-10-07 11:43 UTC, merged